# Generated by Django 2.0.9 on 2018-10-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Types of services provided/', max_length=100)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
